#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
#Browser
browser = chrome
#Secret keys
username = admin
secret = admin123
#Implicitwait (in seconds)
implicitWait = 10
#Explicitwait (in seconds)
explicitWait = 30